---
meta:
  name: cloudfoundry-utils
  target: sw

  url: https://ci.starkandwayne.com

  initial_version: 1.0.0

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner: cloudfoundry-community
    repo:  cloudfoundry-utils
    private_key:  (( vault "secret/pipelines/cloudfoundry-utils/github:private" ))
    access_token: (( vault "secret/pipelines/cloudfoundry-utils/github:token" ))
  slack:
    webhook: (( vault "secret/pipelines/cloudfoundry-utils/slack:webhook" ))
    channel: "#botspam"
